#include <string>
#include <vector>

//----------------------------------------------------------------------------------------------------

std::vector<std::string> input_files;

void InitInputFiles()
{
	input_files = {
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314250.0_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314250.10_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314250.11_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314250.12_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314250.13_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314250.14_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314250.15_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314250.16_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314250.17_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314250.1_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314250.2_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314250.3_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314250.4_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314250.5_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314250.6_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314250.7_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314250.8_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314250.9_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.0_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.10_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.11_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.12_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.13_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.14_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.15_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.16_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.17_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.18_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.19_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.1_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.20_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.21_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.22_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.23_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.24_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.25_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.26_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.27_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.28_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.29_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.2_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.30_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.31_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.32_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.33_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.34_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.35_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.36_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.37_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.38_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.39_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.3_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.40_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.41_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.42_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.43_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.44_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.45_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.46_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.47_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.4_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.5_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.6_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.7_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.8_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314255.9_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314267.0_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314267.1_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314267.2_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314267.3_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314267.4_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314267.5_re_reco.root",
		"root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version6/run_314267.6_re_reco.root"
	};
}
